spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbook
    username: root
    password: rltmdals1212
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
    defer-datasource-initialization: true